extends SceneTree

const Contracts = preload("res://scripts/contracts.gd")
var failed := 0
func check(ok: bool, text: String) -> void:
	if not ok:
		failed += 1
		push_error(text)
func _initialize() -> void:
	var run = Contracts.new()
	run.begin()
	check(run.enabled and run.stage == 0 and run.credits == 0, "fresh campaign")
	check(run.quota(2) == 6 and run.duration() == 240, "first contract tuning")
	run.ship(1, true)
	run.ship(1, true)
	check(run.earned == 15 and run.deliveries == 1 and run.relays == 1, "duplicate cargo reward rejected")
	run.replace_cargo(1)
	run.ship(1, false)
	check(run.earned == 25, "new lifecycle may earn reward")
	run.finish(false)
	check(run.credits == 0 and not run.won, "failed attempt banks nothing")
	run.prepare()
	run.ship(1, false)
	run.finish(true)
	run.finish(true)
	check(run.credits == 30, "completion credits exactly once")
	check(not run.buy("boots", 22), "guest cannot spend bank")
	check(run.buy("boots", 1) and run.credits == 10 and run.boots == 1, "host upgrade deducts cost")
	check(not run.buy("time", 1), "insufficient credit denied")
	check(not run.vote(99, [1,22]), "outsider vote rejected")
	check(not run.vote(22, [1,22]) and not run.vote(22, [1,22]), "one member/duplicate cannot advance")
	check(run.vote(1, [1,22]), "all members agree")
	check(run.advance() and run.stage == 1 and run.quota(2) == 8, "next contract retains upgrades")
	check(not run.buy("boots", 1) and not run.advance(), "no purchases/advance during contract")
	run.ship(1, true)
	run.finish(true)
	run.advance()
	run.finish(true)
	check(run.finished and run.stage == 2 and not run.advance(), "third contract concludes run")
	var copy = Contracts.new()
	copy.apply_snapshot(run.snapshot())
	check(copy.finished and copy.credits == run.credits and copy.boots == 1, "campaign metadata round trip")
	print("CONTRACTS %s" % ("PASS" if failed == 0 else "FAIL"))
	quit(1 if failed else 0)
