using System;
using System.Collections.Generic;
using UnityEngine;
namespace NoReturns.CarryLab {
// English remains the source copy. Each process renders its own chosen language.
public static class CarryLanguage {
    public static bool Korean {get;private set;}=true;
    static bool persist;
    static string preference="NoReturns.Language";
    public static Font Font {get;private set;}
    public static void Initialize(string testFolder){
        persist=testFolder==null;
        preference=testFolder==null?"NoReturns.Language":"NoReturns.Language.Test."+testFolder;
        Korean=!persist||PlayerPrefs.GetString(preference,"ko")!="en";
        Font=Resources.Load<Font>("Fonts/NotoSansKR-Regular");
    }
    public static void Toggle(){Korean=!Korean;if(!persist)return;try{PlayerPrefs.SetString(preference,Korean?"ko":"en");PlayerPrefs.Save();}catch(PlayerPrefsException){Debug.LogWarning("Language changed for this session; preference could not be saved.");}}
    public static string Text(string english){
        if(!Korean)return english;
        if(Ko.TryGetValue(english,out var value))return value;
        if(english.StartsWith("Host failed: ",StringComparison.Ordinal))return "방을 만들지 못했습니다. 이미 열린 방이나 네트워크 설정을 확인하세요.";
        if(english.StartsWith("Join failed: ",StringComparison.Ordinal))return "참가하지 못했습니다. 주소와 방 상태를 확인하세요.";
        return english;
    }
    public static readonly Dictionary<string,string> Ko=new Dictionary<string,string>{
        {"DELIVERY MANIFEST","배송 목록"},
        {"SHIP TERMINAL","우주선 단말기"},
        {"DELIVERED","배송 완료"},
        {"AVAILABLE","배송 가능"},
        {"{0}: {1} left / bundle +{2} CR","{0}: 남은 배송 {1}건 / 묶음 +{2} CR"},
        {"Choose parcels aboard / find the address in its district.","우주선에서 화물을 고르고 해당 구역의 주소를 찾으세요."},

        {"REVIVAL / 100 UNBANKED CR","부활 / 미정산 보상 100 CR"},
        {"CANCEL DEPARTURE","출발 취소"},
        {"AUTOMATIC DEPARTURE / CANNOT CANCEL","자동 출발 / 취소 불가"},
        {"GROSS {0} / REVIVAL -{1} / RETURN -{2} / PAID {3} CR","보상 {0} / 부활 -{1} / 복귀 -{2} / 지급 {3} CR"},
        {"UNBANKED {0} CR / REVIVAL 100 CR\nOutside crew cost 100 CR each at departure.","미정산 {0} CR / 부활 100 CR\n출발 시 밖에 남은 동료당 복귀 비용 100 CR"},
        {"VISIT FAILED / NO PAY","현장 실패 / 보상 없음"},
        {"VISIT SETTLED","철수 정산 완료"},
        {"AUTOMATIC DEPARTURE / RETURN NOW","자동 출발 준비 / 지금 복귀하세요"},
        {"DEPARTURE STARTED / RETURN NOW","출발 준비 / 지금 복귀하세요"},
        {"REVIVE EMPLOYEE {0} / 100 CR","직원 {0} 부활 / 100 CR"},
        {"REVIVING {0} / {1}s","직원 {0} 부활 중 / {1}초"},
        {"Not enough unbanked earnings. Deliver more or depart.","미정산 보상이 부족합니다. 추가 배송하거나 철수하세요."},
        {"Select one eliminated employee. One revival at a time.","탈락한 직원을 선택하세요. 한 번에 한 명만 부활합니다."},
        {"ELIMINATED / wait for ship revival or departure","탈락 / 선내 부활 또는 철수를 기다리세요"},
        {" hold to self-revive / two chances per landing"," 유지로 자가 소생 / 착륙당 2회"},
        {"DOWN / teammate rescue needed","다운 / 동료의 구조가 필요합니다"},
        {"WALLET {0} / UNBANKED {1} CR / HP {2}","자금 {0} / 미정산 {1} CR / 체력 {2}"},
        {"ELIMINATED","탈락"},
        {"Revival started / fee deducted","부활 시작 / 비용 차감"},
        {"Revival unavailable / eliminated crew, free chamber and 100 unbanked CR required","부활 불가 / 탈락자·빈 부활실·미정산 100 CR 필요"},
        {"Departure started / crew outside may be left behind","출발 준비 / 밖의 동료는 남겨질 수 있습니다"},
        {"Departure canceled","출발 취소"},
        {"Visit failed / unbanked earnings lost","현장 실패 / 미정산 보상 상실"},
        {"Departure complete / payout secured","출발 완료 / 보상 지급"},

        {"BOT / ","자동 동료 / "},{"YOU + BOT / safe practice · ","나 + 자동 동료 / 안전한 연습 · "},
        {"Move freely; the bot follows and demonstrates nearby","자유롭게 이동하세요. 동료가 근처에서 행동을 반복합니다"},
        {"Idle","대기"},{"Following","따라오기"},{"Walking / sidestep","걷기 / 옆걸음"},
        {"Slow walk","느린 이동"},{"Baton","진압봉"},{"Carry parcel","상자 운반"},{"Put down","내려놓기"},
        {" move · "," 이동 · "},{" jump · Esc settings"," 점프 · Esc 설정"},
        {"FLATBED / SHIP TERMINAL","FLATBED / 우주선 단말"},
        {"CONTROLS & SETTINGS","조작과 설정"},
        {"CINDER DEPOT / BAY 04 · shared crew wallet","CINDER DEPOT / BAY 04 · 직원 공용 잔액"},
        {"Click a binding, then press a key. Esc cancels. Esc always closes menus.","변경할 조작을 클릭하고 새 키를 누르세요. Esc 취소 · 메뉴 닫기는 Esc 고정"},
        {"Direct LAN / choose host or join. Menus do not pause the world.","직접 LAN 연결 / 방 만들기 또는 참가하기 · 메뉴를 열어도 게임은 진행됩니다"},
        {"HOST LAN ADDRESS","방장 LAN 주소"},
        {"Use opens the ship terminal aboard. Buy supplies there.\nPlace with left click, rotate with right click, adjust reach with wheel.","우주선에 탑승한 뒤 사용 키로 단말을 열어 진행과 구매를 합니다.\n좌클릭 놓기 · 우클릭 유지 회전 · 휠로 운반 거리 조절"},
        {"RESTORE DEFAULTS","기본값 복원"},
        {"BACK","뒤로"},
        {"CLOSE / Esc","닫기 / Esc"},
        {"DECOY BEACON / 120 CR","유인 신호기 / 120 CR"},
        {"One shared device. Two 8-second signals per shift. Carry from the ship; place on field ground.","직원 공용 장비 1개. 근무마다 2회, 각 8초 신호. 우주선에서 들고 나가 현장 바닥에 놓으세요."},
        {"ABOARD {0}/{1} / WALLET {2} CR","탑승 {0}/{1}명 / 잔액 {2} CR"},
        {"SELECT CINDER ROUTE","CINDER 항로 선택"},
        {"DEPART / CINDER DEPOT","출발 / CINDER DEPOT"},
        {"PREPARE NEXT SHIFT","다음 근무 준비"},
        {"CONFIRM RETURN / 0 CR","귀환 확정 / 보수 0 CR"},
        {"RETURN WITHOUT RECEIPT","영수증 없이 귀환"},
        {"RETURN & SETTLE","귀환하고 정산"},
        {"Host controls departure, return and shared purchases","출발·귀환·공용 장비 구매는 방장이 진행합니다"},
        {"Wait for every crew member to board","모든 직원이 탑승해야 출발·귀환할 수 있습니다"},
        {"Returning now pays 0 CR. Click again to confirm.","지금 귀환하면 보수는 0 CR입니다. 다시 클릭하면 귀환합니다."},
        {"Crew ready / confirm using the button","전원 탑승 완료 / 버튼으로 진행하세요"},
        {"Select the route or prepare the next shift","항로를 선택하거나 다음 근무를 준비하세요"},
        {"INSUFFICIENT FUNDS / 120 CR","잔액 부족 / 120 CR 필요"},
        {"USES {0}/2 / SHARED DEVICE","사용 {0}/2회 / 공용 장비"},
        {"Buy during preparation or shift report","우주선 준비·근무 정산 중 구매할 수 있습니다"},
        {"Press a key or mouse button / Esc cancels","새 키 또는 마우스 버튼을 누르세요 / Esc 취소"},
        {"Already assigned / choose another key","이미 사용 중인 키입니다 / 다른 키를 선택하세요"},
        {"Controls saved","조작을 저장했습니다"},
        {"Defaults restored","기본값을 복원했습니다"},
        {"Settings apply this session / save failed","설정은 이번 실행에 적용됩니다 / 저장 실패"},
        {"Mouse sensitivity","마우스 감도"},
        {"Forward","앞으로"},
        {"Back","뒤로 이동"},
        {"Left","왼쪽 이동"},
        {"Right","오른쪽 이동"},
        {"Use / rescue","사용 / 구조"},
        {"Release","즉시 놓기"},
        {"Place / baton","바닥에 놓기 / 진압봉"},
        {"Rotate item","물건 회전"},
        {"Jump","점프"},
        {"Quiet walk","조용히 걷기"},
        {"Call","소리 내기"},
        {"Field log","현장 기록"},
        {"Reset lab","운반 실험 초기화"},
        {"Approaching for rescue","구조 시연 위치로 이동"},
        {"Down / waiting for rescue","다운 / 구조 대기"},
        {"Getting up","일어나는 중"},
        {"Hold use near the downed bot to rescue","쓰러진 동료 곁에서 사용 키를 길게 눌러 구조"},
        {"Bot approaching for rescue practice","동료가 구조 시연을 위해 다가오는 중"},
        {" restart rescue demo"," 구조 시연 다시 시작"},
        {"Placement blocked / aim at clear nearby ground","놓을 공간이 없습니다 / 가까운 빈 바닥을 조준하세요"},
        {"Parcel placed","화물을 바닥에 놓았습니다"},
        {" place · "," 바닥에 놓기 · "},
        {" hold to rotate · Wheel reach · "," 유지 회전 · 휠 거리 · "},
        {" release"," 즉시 놓기"},
        {" place beacon · "," 신호기 놓기 · "},
        {" OPEN SHIP TERMINAL"," 우주선 단말 열기"},
        {"RESCUING {0}% / keep holding ","구조 중 {0}% / 계속 누르기 "},
        {" hold to rescue"," 유지해 구조"},
        {" quiet · "," 조용히 걷기 · "},{" call · "," 소리내기 · "},{" baton"," 진압봉"},{" baton ready in {0}s"," 진압봉 준비 {0}초"},
        {"LISTENER / watch the warning; keep quiet","리스너 / 경고를 보고 피하세요 · 조용히 이동"},
        {" COLLECT RECEIPT"," 영수증 회수"},
        {" INSPECT TERMINAL"," 단말 조사"},
        {" PICK UP BEACON"," 신호기 들기"},
        {" PICK UP PARCEL"," 화물 들기"},
        {"Aim at a nearby object to use it / Esc settings","가까운 물건을 조준해 사용하세요 / Esc 설정"},
        {"Mouse look / Wheel reach / Esc settings","마우스 시점 · 휠 운반 거리 · Esc 설정"},
        {"SHIP / Open terminal to select CINDER DEPOT","우주선 / 단말에서 CINDER DEPOT 항로를 선택하세요"},
        {"CINDER DEPOT / Board together, then depart at terminal","CINDER DEPOT / 전원 탑승 후 우주선 단말에서 출발하세요"},
        {"Deliver parcel onto BAY 04 floor. Return through ship terminal.","BAY 04 표시 바닥에 화물을 배송하세요. 귀환은 우주선 단말에서 진행합니다."},
        {"Collect the receipt at BAY 04. Return aboard and settle at ship terminal.","BAY 04에서 영수증을 회수하세요. 우주선에 탑승해 단말에서 귀환·정산하세요."},
        {"SHIFT REPORT / Prepare next shift at ship terminal","근무 정산 / 우주선 단말에서 다음 근무를 준비하세요"},
        {"CINDER / DELIVERY LOOP","CINDER / 배송 사이클"},
        {"Direct LAN / TCP 27842\nSame PC: 127.0.0.1\nBAY 04 receipt / return aboard to settle.","직접 LAN / TCP 27842\n같은 PC: 127.0.0.1\nBAY 04 수령 · 우주선 귀환 후 정산"},
        {"WASD move / Mouse look / E ship action / Esc menu","WASD 이동 · 마우스 시점 · E 우주선 진행 · Esc 메뉴"},
        {"[E] SHIP ACTION / all crew aboard to depart or return","E 우주선 진행 · 출발/귀환 시 전원 탑승"},
        {"RECEIPT {0} + RETURN {1} CR","수령 {0} + 귀환 {1} CR"},
        {"CINDER / FOUR-PLAYER MAP TEST","CINDER / 4인 맵 테스트"},
        {"CREW {0}/4","직원 {0}/4"},
        {"[E] Carry / [Q] Set down / Space jump / Esc menu","E 들기 · Q 내려놓기 · Space 점프 · Esc 메뉴"},
        {"WASD move / Mouse look / R reset (host)","WASD 이동 · 마우스 시점 · R 초기화(방장)"},
        {"Map mismatch / use the same test build","맵이 다릅니다. 같은 테스트 실행본으로 접속하세요."},
        {"Direct LAN / TCP 27842\nSame PC: 127.0.0.1\nMap test / movement and carrying only.","직접 LAN / TCP 27842\n같은 PC: 127.0.0.1\n맵 시험 / 이동과 운반"},
        {"WALLET {0} CR / CREW {1}/4","잔액 {0} CR / 직원 {1}/4"},
        {"EMPTY","빈자리"},
        {"DOWN","구조 필요"},
        {"CARGO","화물 운반"},
        {"BEACON","신호기 운반"},
        {"ABOARD","우주선"},
        {"IN FIELD","현장"},
        {"YOU","나"},
        {"[E] Interact / Hold E rescue / LMB baton / Tab log / Esc menu","E 상호작용 · E 유지 구조 · 왼쪽 클릭 충격봉 · Tab 기록 · Esc 메뉴"},
        {"RESCUING {0}% / keep holding E","구조 중 {0}% / E를 계속 누르세요"},
        {"WASD move / Mouse look / Shift quiet walk","WASD 이동 · 마우스 시점 · Shift 조용히 걷기"},
        {"Protocol mismatch / use the same game build","게임 버전이 다릅니다. 같은 실행본으로 접속하세요."},
        {"RECEIPT COLLECTED","영수증 회수 완료"},{"TAKE RECEIPT [E]","영수증 가져가기 [E]"},{"PRINTING RECEIPT","영수증 출력 중"},{"SCANNING","화물 확인 중"},{"PLACE PARCEL","화물을 놓으세요"},{"STANDBY","대기 중"},
        {"Receipt collected / return aboard to get paid","영수증을 챙겼습니다 / 우주선에 돌아가 정산하세요"},
        {"Collect receipt at terminal [E] / No pay until return","단말기에서 [E]로 영수증을 챙기세요 / 귀환 전에는 미지급"},
        {"COLLECT RECEIPT [E] at terminal / Bring it back aboard, then [E] RETURN TO GET PAID","단말기에서 [E] 영수증 회수 / 우주선으로 가져와 [E] 귀환·정산"},
        {"PLACE PARCEL ON MARKED FLOOR","표시 안에 화물을 내려놓으세요"},
        {"SCANNING / KEEP CLEAR","확인 중 / 화물을 움직이지 마세요"},
        {"DELIVERY CONFIRMED","배송 완료"},
        {"TERMINAL STANDBY","단말 대기"},
        {"SUPPRESSOR / steady hum","억제장치 / 일정한 작동음"},
        {"SUPPRESSOR / irregular signal - plan your return","억제장치 / 불규칙한 신호 — 귀환을 준비하세요"},
        {"SUPPRESSOR / failing - movement at the east gate","억제장치 / 붕괴 임박 — 동쪽 문에서 무언가 움직입니다"},
        {"SUPPRESSOR / failing - movement beyond the east boundary","억제장치 / 붕괴 임박 — 동쪽 경계 밖에서 무언가 움직입니다"},
        {"SUPPRESSOR OFF / outer creature entering - return to ship","억제장치 정지 / 외곽 생물 진입 — 우주선으로 대피하세요"},
        {"Partner left / emergency recovery / secured pay retained","동료가 나갔습니다 / 긴급 회수 완료 / 확보한 보수 유지"},
        {"Shift in progress / wait for host to prepare next shift","근무 진행 중 / 방장이 다음 근무를 준비하면 참가할 수 있습니다"},
        {"Room full / wait for a free crew slot","방이 가득 찼습니다 / 직원 자리가 생기면 다시 참가하세요"},
        {CarryClues.FirstTitle,"01 / 끝난 근무"},
        {CarryClues.FirstBody,"정비 기록: 이 배송소는 열아홉 근무 전에 폐쇄됐다.\n단말은 따뜻하다. 급지 롤러에는 마르지 않은 잉크가 묻어 있다.\n누군가 계속 사용하고 있다."},
        {CarryClues.SecondTitle,"02 / 이미 수령함"},
        {CarryClues.SecondBody,"화물 CND-041: 수령 완료.\n영수증의 날짜는 우리 우주선이 착륙하기 전이다.\n수령인 서명: 직원 00.\n셔터 너머에서는 아무도 대답하지 않는다."},
        {"Inspect clues during the delivery shift","현장에 도착한 뒤 단서를 조사하세요"},
        {"Aim at a nearby terminal and press E","가까운 단말을 바라보고 E로 조사하세요"},
        {"Recorder idle / deliver the parcel first","수령 기록기 대기 중 / 먼저 화물을 배송하세요"},
        {"Already in the shared field log","이미 공용 현장 기록에 있습니다"},
        {"Clue shared / Tab to read safely aboard","단서를 공유했습니다 / 우주선에서 Tab으로 안전하게 읽으세요"},
        {"Shift quiet walk / C call / LMB baton / Hold E rescue / E inspect / Tab field log","Shift 조용히 걷기 / C 소리 / 왼쪽 클릭 충격봉 / E 유지 구조 / E 조사 / Tab 기록"},
        {"[E] Inspect terminal / shared field log","[E] 단말 조사 / 공용 현장 기록"},
        {"CINDER DEPOT / SHARED FIELD LOG","신더 배송소 / 공용 현장 기록"},
        {"The world keeps moving. Read aboard. Records reset on next arrival; not saved after exit.","읽는 동안에도 현장은 움직입니다. 우주선에서 읽으세요. 기록은 다음 도착 때 초기화되며 종료 후 저장되지 않습니다."},
        {"UNRECORDED / inspect the site","미발견 / 현장을 조사하세요"},
        {"No entry yet. A teammate can share it by inspecting a terminal.","아직 기록이 없습니다. 동료가 단말을 조사해도 함께 공유됩니다."},
        {"Not discovered","미발견"},
        {"CLOSE / Tab or Esc","닫기 / Tab 또는 Esc"},
        {"SHIP SUPPLY / saved host license","우주선 보급 / 방장 저장 사용권"},
        {"New host progress","새 방장 진행을 시작합니다"},
        {"Host progress loaded","방장의 저장된 진행을 불러왔습니다"},
        {"Progress saved on host PC","방장 PC에 진행 저장 완료"},
        {"Recovered previous backup; recent changes may be missing","이전 백업으로 복구했습니다. 최근 변경 일부가 없을 수 있습니다"},
        {"Cannot read host save. Original files preserved.","저장 파일을 읽을 수 없어 방을 열지 못했습니다. 원본 파일은 보존했습니다"},
        {"Newer save version; update the game. Files preserved.","더 최신 버전의 저장입니다. 게임을 업데이트하세요. 파일은 보존했습니다"},
        {"SAVE FAILED / progress is not on disk; retrying","저장 실패 / 진행이 파일에 반영되지 않았습니다. 다시 시도 중입니다"},
        {"Using host progress / personal save unchanged","방장 진행을 함께 사용 중 / 내 저장에는 반영하지 않습니다"},
        {"[E] ship action / Blue floor: ship / Gold floor: reception / Host save","[E] 우주선 조작 / 파란 바닥: 우주선 / 금색 바닥 표시: 수령소 / 방장 저장"},
        {"Beacon license purchased","유인 신호기 사용권을 구매했습니다"},
        {"Purchase unavailable: host, ship/report, 120 CR required","구매 불가: 방장이 우주선 준비·정산 중 120 CR로 구매할 수 있습니다"},
        {"Contract changed","계약 위험도를 변경했습니다"},
        {"Select route aboard after first delivery; host only","첫 배송 성공 후 우주선에서 항로 선택 중 방장이 변경할 수 있습니다"},
        {"Beacon deployed","유인 신호기를 설치했습니다"},
        {"Aim at yard floor within 8m, empty hands; beacon must be ready","빈손으로 8m 안 작업장 바닥을 조준하세요. 사용 횟수와 활성 상태를 확인하세요"},
        {"SHIP SUPPLY / session license","우주선 보급 / 이번 세션 사용권"},
        {"Wallet {0} CR / Beacon {1}","공용 잔액 {0} CR / 신호기 {1}"},
        {"OWNED","구매 완료"},
        {"120 CR","120 CR"},
        {"Buy beacon license","신호기 사용권 구매"},
        {"Purchase spawns beacon aboard. E carry / Q place. Two uses per shift, 8 seconds each.","구매하면 우주선에 신호기가 생깁니다. E 운반 / Q 내려놓기. 근무마다 2회, 각 8초 작동. 위·아래 키로 메뉴 선택, E 확인."},
        {"Change selected contract","선택한 계약 위험도 변경"},
        {"RISK / receipt 450 + return 180","위험 / 배송 450 + 귀환 180"},
        {"STANDARD / receipt 300 + return 120","일반 / 배송 300 + 귀환 120"},
        {"{0} / Beacon {1}/2 ({2}s) / E carry / Q place","{0} / 신호기 {1}/2회 ({2}초) / E 들기 / Q 내려놓기"},
        {"RISK","위험 계약"},
        {"STANDARD","일반 계약"},
        {"Shift quiet walk / Q call / G shove (empty hands) / Hold R near teammate to rescue","Shift 조용히 걷기 / C 소리내기 / G 빈손 밀치기 / 동료 곁에서 E를 눌러 구조"},
        {"LISTENER: ATTACK WARNING - MOVE AWAY","리스너: 공격 예고! 뒤로 피하세요"},
        {"LISTENER: STUNNED","리스너: 밀쳐져 잠시 멈춤"},
        {"LISTENER: INVESTIGATING SOUND","리스너: 마지막 소음 위치를 조사 중"},
        {"LISTENER: PATROLLING / keep quiet","리스너: 순찰 중 / 조용히 이동하세요"},
        {"Rescue {0}% / Baton cooldown {1}s","구조 {0}% / 충격봉 재사용 {1}초"},
        {"DOWN / wait for teammate rescue. All down: emergency recovery.","행동 불능 / 동료의 구조를 기다리세요. 전원 다운 시 긴급 회수됩니다."},
        {"Employee down / parcel released","직원이 쓰러져 화물을 놓았습니다"},
        {"Emergency recovery / secured pay retained","긴급 회수 완료 / 확보한 배송 보수는 유지됩니다"},
        {"NO RETURNS / LISTENER TEST","NO RETURNS / 리스너 실험"},{"LISTENER TEST","리스너 실험"},{"TEAMMATE DOWN / put cargo down, approach and hold E","동료가 쓰러졌습니다 / 화물을 내려놓고 가까이서 E를 누르세요"},
        {"Choose HOST or enter the host's LAN address.","방을 만들거나 방장의 내부 네트워크 주소를 입력하세요."},
        {"HOST / waiting for partner","방장 / 동료를 기다리는 중"},
        {"Connecting...","연결 중..."},
        {"Disconnected. Host or join again.","연결이 종료됐습니다. 방을 만들거나 다시 참가하세요."},
        {"Connection failed. Check address / host / firewall.","연결에 실패했습니다. 주소·방장 접속·방화벽 설정을 확인하세요."},
        {"CLIENT / connected","참가자 / 연결됨"},
        {"Connection timed out.","연결 시간이 초과됐습니다."},
        {"HOST / partner connected","방장 / 동료가 참가했습니다"},
        {"HOST / partner left","방장 / 동료가 나갔습니다"},
        {"Host connection lost.","방장과 연결이 끊어졌습니다."},
        {"Host timed out.","방장의 응답이 없어 연결을 종료했습니다."},
        {"Parcel set down","화물을 내려놓았습니다"},
        {"Parcel held","화물을 들었습니다"},
        {"NO RETURNS / CARRY TEST","NO RETURNS / 운반 실험"},
        {"NO RETURNS / DELIVERY LOOP","NO RETURNS / 배송 실험"},
        {"HOST","방 만들기"},{"JOIN","참가하기"},{"RESUME","계속하기"},{"LEAVE SESSION","방 나가기"},{"QUIT","게임 종료"},
        {"Direct LAN / TCP 27841\nSame PC: 127.0.0.1\nAllow host through Windows Firewall if prompted.","내부 네트워크 직접 연결 / TCP 27841\n같은 PC에서 참가: 127.0.0.1\n방화벽 안내가 나오면 게임 연결을 허용하세요."},
        {"WASD move / Mouse look / E interact / Q set down\nSpace jump (empty hands) / R reset (host)","WASD 이동 / 마우스 시점 / E 상호작용 / Q 내려놓기\nSpace 빈손 점프 / R 실험실 초기화 (방장)"},
        {"WASD move / Mouse look / E interact / Q set down\nSpace jump (empty hands) / E ship action","WASD 이동 / 마우스 시점 / E 상호작용 / Q 내려놓기\nSpace 빈손 점프 / E 선내 항로·귀환"},
        {"FOV","시야각"},{"CARRY TEST","운반 실험"},{"DELIVERY LOOP","배송 실험"},{"Host","방장"},{"Client","참가자"},{"CREW","직원"},
        {"Move the parcel through the passage and onto the marked floor.","통로를 지나 화물을 선반 위에 내려놓으세요."},
        {"SHARED WALLET {0} CR / RECEIPT {1} / RETURN {2}","공용 잔액 {0} CR / 배송 보수 {1} / 귀환 보수 {2}"},
        {"[E] ship action / Blue floor: ship / Gold floor: reception / Session only","[E] 선내 행동 / 청록 바닥: 우주선 / 황색 바닥 표시: 수령소 / 종료하면 잔액 초기화"},
        {"[Q] SET DOWN   /   HANDS OCCUPIED","[Q] 내려놓기 / 화물을 들고 있습니다"},
        {"[E] PICK UP nearby parcel   /   WASD move   /   Esc menu","[E] 가까운 화물 들기 / WASD 이동 / Esc 메뉴"},
        {"SHIP / [E] Select CINDER DEPOT route","우주선 / [E] 신더 디포 항로 선택"},
        {"CINDER DEPOT selected / Crew aboard, then [E] AUTO ARRIVE","신더 디포 선택됨 / 전원 탑승 후 [E] 자동 이동·도착"},
        {"Deliver sealed parcel onto the marked reception floor. [E] aboard: abort and return","밀봉 화물을 황색 바닥 표시 안에 내려놓으세요. 선내 [E]: 배송을 포기하고 귀환"},
        {"RECEIPT CONFIRMED / Return to blue ship zone together, then [E] RETURN","수령 완료 / 청록색 선내 구역에 함께 모인 뒤 [E] 귀환"},
        {"SHIFT REPORT / [E] inside ship: prepare next shift","근무 정산 / 선내에서 [E] 다음 근무 준비"}
    };
}
}
