extends RefCounted

static var language := "ko"
const STRINGS := {
	"map_mismatch": ["Different map files. Use the same saved map/build as the host.", "맵 파일이 다릅니다. 방장과 같은 저장 맵/빌드를 사용하세요."],
	"lesson_0": ["WASD: move · Mouse: look · Space: jump · H: help", "WASD: 이동 · 마우스: 둘러보기 · Space: 점프 · H: 도움말"],
	"lesson_1": ["Approach a package and press E to pick it up.", "상자에 다가가 E를 눌러 들어 보세요."],
	"lesson_2": ["Left click: throw · E: put down / catch · Q: ping", "왼쪽 클릭: 던지기 · E: 내려놓기 / 받기 · Q: 위치 알림"],
	"lesson_3": ["Read the A/B label and deliver to its matching bay.", "상자의 A/B 라벨과 같은 배송구에 넣으세요."],
	"lesson_4": ["Try a team relay · F: reverse belt · H: help · Esc: settings", "동료와 릴레이에 도전하세요 · F: 벨트 전환 · H: 도움말 · Esc: 설정"],
	"version_mismatch": ["Different game versions. Update every player to the same build.", "게임 버전이 다릅니다. 모두 같은 최신 빌드로 갱신하세요."],
	"relay": ["TEAM RELAY! Deliver this package for a bonus.", "팀 릴레이! 이 상자를 배송하면 추가 보상을 받습니다."],
	"hopper_name": ["HOPPER", "점프 상자"],
	"hopper_rest": ["HOP IN %.1fs", "%.1f초 뒤 점프 준비"],
	"hopper_windup": ["JUMP IN %.1fs!", "%.1f초 뒤 점프!"],
	"hopper_paused": ["HELD / JUMP PAUSED", "들고 있음 / 점프 대기"],
	"hopper_airborne": ["HOP!", "폴짝!"],
	"ping_here": ["%02d / HERE! ↓", "%02d / 여기요! ↓"],
	"ping_cargo": ["%02d / THIS PACKAGE! ↓", "%02d / 이 상자요! ↓"],
	"overtime": ["ACCEPT OVERTIME", "추가 근무 동의"],
	"overtime_votes": ["OVERTIME? %d / %d ACCEPTED", "추가 근무? %d / %d명 동의"],
	"bonus_playing": ["BONUS SHIFT / 60 SECONDS", "보너스 근무 / 60초"],
	"bonus_done": ["BONUS FINISHED / Base shift secured", "보너스 종료 / 기본 근무 성공 유지"],
	"result": ["%d / %d deliveries · %d seconds\nShipment seed: %d", "%d / %d개 배송 · %d초\n배송 시드: %d"],
	"base_secured": ["BASE SHIFT COMPLETE!", "기본 근무 성공!"],
	"sensitivity": ["MOUSE SENSITIVITY: %.2fx", "마우스 감도: %.2f배"],
	"lever": ["F  REVERSE CONVEYOR", "F  컨베이어 방향 전환"],

	"subtitle": ["The packages are alive. Ship them anyway.", "택배가 살아 있습니다. 그래도 배송은 해야죠."],
	"foundation": ["06 / NIGHT SHIFT DEPOT", "06 / 야간 물류센터"],
	"intro": ["Some packages refuse to sit still.\nPut them to work.", "택배가 가만히 있질 않네요.\n일을 시켜보세요."],
	"scope": ["Four cargo types. Read the label. Make it work.", "화물 네 종류. 라벨을 읽고 함께 배송하세요."],
	"practice": ["PRACTICE ALONE", "혼자 연습하기"],
	"host": ["HOST / 2–4 WORKERS", "방 만들기 / 2~4인"],
	"join": ["JOIN DEPOT", "창고 참가하기"],
	"address": ["Host address (same PC: 127.0.0.1)", "방장 주소 (같은 PC: 127.0.0.1)"],
	"development": ["DEVELOPMENT PROTOTYPE / 0.7.7\nLocal / LAN connection · Steam invites not connected", "개발용 프로토타입 / 0.7.7\n로컬·LAN 연결 · Steam 친구 초대 미연결"],
	"menu_note": ["Read the A / B label.\nWrong bay? Back to intake.", "A / B 라벨을 확인하세요.\n잘못 보내면 입고 구역으로!"],
	"controls": ["WASD  Move    MOUSE  Look    SPACE  Jump    Q  Ping    F  Reverse belt\nE  Pick up / catch / put down    LEFT CLICK  Throw    ESC  Menu", "WASD  이동    마우스  둘러보기    SPACE  점프    Q  위치 알림    F  벨트 전환\nE  집기 / 받기 / 내려놓기    왼쪽 클릭  던지기    ESC  메뉴"],
	"waiting": ["WAITING FOR CREW", "동료를 기다리는 중"],
	"ready": ["CREW READY / Host starts the shift", "직원 집합 완료 / 방장이 근무를 시작하세요"],
	"playing": ["MATCH THE A / B LABEL", "A / B 라벨에 맞게 배송하세요"],
	"won": ["SHIFT COMPLETE", "근무 완료"],
	"lost": ["TIME'S UP / Try another shift", "시간 종료 / 다시 도전하세요"],
	"connecting": ["CONNECTING… (up to 10 seconds)", "연결 중… (최대 10초)"],
	"score": ["%d / %d SHIPPED", "%d / %d 배송 완료"],
	"crew": ["%d / 4 WORKERS", "%d / 4 직원"],
	"solo": ["SOLO PRACTICE", "혼자 연습 중"],
	"start": ["START SHIFT", "근무 시작"],
	"restart": ["ANOTHER SHIFT", "다시 근무하기"],
	"leave": ["LEAVE TO MENU", "나가서 메뉴로"],
	"resume": ["BACK TO WORK", "근무로 돌아가기"],
	"pause_title": ["TAKING A BREATHER", "잠깐 쉬어가기"],
	"pause_note": ["The shift keeps running while this menu is open.", "이 메뉴가 열려 있어도 근무 시간은 흐릅니다."],
	"carrying": ["E  Put down   /   LEFT CLICK  Throw toward marker", "E  내려놓기   /   왼쪽 클릭  착지 표지 쪽으로 던지기"],
	"near": ["E  Pick up / catch", "E  집기 / 받기"],
	"far": ["Find the crate at INTAKE. Match its A / B label.", "입고 구역의 화물을 찾아 라벨에 맞게 보내세요."],
	"busy": ["Your coworker has the crate. Get ready to catch!", "동료가 화물을 들고 있어요. 받을 준비를 하세요!"],
	"shipped": ["DELIVERED! Next crate in a moment.", "배송 완료! 곧 다음 화물이 나옵니다."],
	"wrong_bay": ["WRONG BAY / Returning to intake…", "잘못된 배송구 / 입고 구역으로 반송 중…"],
	"recovered": ["Cargo recovered at intake.", "입고 구역으로 화물을 복구했어요."],
	"guest_left": ["Coworker left. Cargo released. Waiting for crew.", "동료가 나갔어요. 화물을 놓고 새 동료를 기다립니다."],
	"host_left": ["Host left. The session has ended.", "방장이 나가서 근무가 끝났어요."],
	"connection_failed": ["Could not connect. Check the host, address and network.", "연결하지 못했어요. 방 개설, 주소와 네트워크를 확인하세요."],
	"host_failed": ["Could not host. Another host may already use this port.", "방을 만들지 못했어요. 같은 포트를 쓰는 방이 있는지 확인하세요."],
	"shift_running": ["This shift already started. Join the next lobby.", "이미 근무 중이에요. 다음 대기실에 참가하세요."],
	"recovery": ["Returning the crate…", "화물을 돌려보내는 중…"],
	"cancel": ["CANCEL CONNECTION", "연결 취소"],
	"prototype": ["NO RETURNS / DEVELOPMENT 0.7.7", "반품 불가 / 개발용 0.7.7"],
	"clinger_name": ["CLINGER", "접착 상자"],
	"clinger_attached": ["STUCK! %.1fs / Sneeze to release.", "붙었어요! %.1f초 / 재채기로 떼어내세요."],
	"clinger_cooldown": ["UNSTUCK / Ready in %.1fs", "떨어졌어요 / %.1f초 뒤 다시 접착"],
	"clinger_ready": ["CLINGER / Touch to stick", "접착 상자 / 닿으면 붙어요"],
	"clinger_tag_attached": ["STUCK %.1fs", "접착 %.1f초"],
	"clinger_tag_cooldown": ["READY IN %.1fs", "대기 %.1f초"],
	"clinger_tag_ready": ["TOUCH TO STICK", "닿으면 접착"],
	"sneezer_name": ["SNEEZER", "재채기 상자"],
	"standard_name": ["STANDARD", "일반 상자"],
	"sneeze_warning": ["SNEEZE IN %.1fs! Watch the nose.", "%.1f초 뒤 재채기! 코 앞을 피하세요."],
	"sneeze_blast": ["ACHOO! Somebody catch that!", "에취! 누가 저 상자 좀 잡아!"],
	"achoo": ["ACHOO!", "에취!"],
	"sound_on": ["CUES: ON  /  Click to mute", "신호음 켜짐  /  누르면 끄기"],
	"sound_off": ["CUES: OFF  /  Click to enable", "신호음 꺼짐  /  누르면 켜기"],
}

static func get_text(key: String) -> String:
	var pair: Array = STRINGS.get(key, [key, key])
	return pair[1 if language == "ko" else 0]

static func toggle() -> void:
	language = "en" if language == "ko" else "ko"
