extends RefCounted
const Copy = preload("res://scripts/copy.gd")
const STRINGS := {
	"settings":["SETTINGS", "설정"],
	"close":["BACK", "돌아가기"],
	"saved":["Changes are saved automatically.", "변경 사항은 자동으로 저장됩니다."],
	"save_failed":["Could not save settings. Check free space and folder permissions.", "설정을 저장하지 못했습니다. 여유 공간과 폴더 권한을 확인하세요."],
	"display":["DISPLAY & CAMERA", "화면과 카메라"],
	"controls":["CONTROLS", "조작"],
	"sound":["SOUND", "소리"],
	"cues":["Gameplay sounds", "게임 효과음"],
	"volume":["Master volume", "전체 음량"],
	"sensitivity":["Mouse sensitivity", "마우스 감도"],
	"fov":["Field of view", "시야각"],
	"invert":["Invert camera Y", "카메라 위아래 반전"],
	"fullscreen":["Borderless fullscreen", "테두리 없는 전체 화면"],
	"vsync":["VSync", "수직 동기화"],
	"fps":["Frame limit", "프레임 제한"],
	"unlimited":["Unlimited", "제한 없음"],
	"rebind":["Select an action, then press a key or mouse button. Esc cancels.\nEsc, Tab, Enter and modifier keys stay reserved for menus.", "바꿀 동작을 누른 뒤 키나 마우스 버튼을 누르세요. Esc는 취소입니다.\nEsc, Tab, Enter와 보조 키는 메뉴용으로 유지됩니다."],
	"listening":["Press a key or mouse button…  Esc: cancel", "키나 마우스 버튼을 누르세요…  Esc: 취소"],
	"conflict":["Already assigned. Change that action first.", "다른 동작에 쓰는 키입니다. 해당 동작부터 변경하세요."],
	"reserved":["This key is reserved. Choose another key.", "메뉴용으로 유지하는 키입니다. 다른 키를 선택하세요."],
	"reset":["RESTORE DEFAULT CONTROLS", "기본 조작으로 되돌리기"],
	"forward":["Move forward", "앞으로 이동"], "back":["Move backward", "뒤로 이동"],
	"left":["Move left", "왼쪽 이동"], "right":["Move right", "오른쪽 이동"],
	"jump":["Jump", "점프"], "interact":["Pick up / put down / catch", "집기 / 내려놓기 / 받기"],
	"throw":["Throw", "던지기"], "ping":["Ping", "위치 알림"], "lever":["Reverse belt", "벨트 전환"],
	"horn":["Airhorn", "경적"], "help":["Shift manual", "근무 안내서"],
	"solo_pause":["Paused. Your shift will wait for you.", "일시정지 중입니다. 근무 시간도 멈췄습니다."],
	"online_pause":["Online shift continues. Your worker is not moving.", "온라인 근무는 계속됩니다. 내 직원의 조작만 멈춥니다."],
	"leave_title":["LEAVE THIS SHIFT?", "이번 근무에서 나갈까요?"],
	"quit_title":["QUIT NO RETURNS?", "반품 불가를 종료할까요?"],
	"leave_note":["The current run will be lost. Completed-run records are kept.", "진행 중인 판은 저장되지 않습니다. 이전 완주 기록은 유지됩니다."],
	"host_leave":["This ends the session for every worker.\nThe current run is not saved.", "방장이 나가면 동료의 근무도 종료됩니다.\n진행 중인 판은 저장되지 않습니다."],
	"confirm":["YES, LEAVE", "나가기"], "keep_playing":["STAY HERE", "계속하기"],
	"solo":["SOLO CAMPAIGN", "혼자 캠페인"],
	"crew_terminal":["CREW CONNECTION", "동료 연결"],
	"join_hint":["Local / LAN playtest\nEnter the host address to join.\nSteam invitations are not connected yet.", "로컬·LAN 플레이테스트\n방장 주소를 입력해 참가하세요.\nSteam 친구 초대는 아직 연결 전입니다."],
	"goal":["DELIVER THE LABEL, NOT THE EXCUSE", "변명 말고 택배를 보내세요"],
	"goal_body":["Pick up a parcel. Read A or B.\nDeliver it to the matching dispatch bay.\nCatch a coworker's throw for a relay bonus.", "상자를 집고 A 또는 B 라벨을 확인하세요.\n같은 글자의 배송구까지 운반하면 됩니다.\n동료가 던진 상자를 받으면 릴레이를 노릴 수 있어요."],
	"waiting_guest":["Waiting for the host to start.", "방장이 근무를 시작할 때까지 기다리세요."],
	"settings_hint":["Esc: menu", "Esc: 메뉴"],
}
static func text(key: String) -> String:
	var pair: Array = STRINGS.get(key, [key,key])
	return pair[1 if Copy.language == "ko" else 0]
