extends "res://tools/apply_postal_art.gd"
func run() -> void:
	map = load(TARGET).instantiate(); root.add_child(map); map.set_process(false)
	for node in map.get_node("Gameplay/Conveyor").get_children():
		if not node.has_node("conveyor_module"): continue
		var parent := node.get_parent(); var at: Vector3 = node.position; parent.remove_child(node); node.free(); instance(parent,"conveyor_module",at)
	for node in map.find_children("Art_*","Node3D",true,false): Art.finish(node)
	for mesh in map.find_children("*","MeshInstance3D",true,false):
		if mesh.material_override is StandardMaterial3D and mesh.material_override.normal_enabled:
			mesh.material_override.normal_scale = 0.025
	# Preview children are regenerated by @tool props. Saving them duplicates the art.
	for p in map.get_node("Gameplay/Reactions").props:
		for child in p.get_children(): child.free()
	map.set_meta("postal_art_01",2)
	own(map)
	var packed := PackedScene.new()
	if packed.pack(map) != OK or ResourceSaver.save(packed,TARGET) != OK: quit(1); return
	map.queue_free(); await process_frame; print("POSTAL ART REFINED"); quit()
